#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from payload_catalog import build_catalog


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "sources.json"
CACHE_ROOT = Path(
    os.environ.get(
        "BLUE_SEC_CACHE",
        Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
        / "blue-sec-hub",
    )
)
UPSTREAMS = CACHE_ROOT / "upstreams"
CANDIDATE_ROOT = CACHE_ROOT / "source-candidates"


def run(*args: str, cwd: Path | None = None) -> str:
    result = subprocess.run(
        args,
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout.strip()


def copy_markdown_tree(source: Path, destination: Path) -> int:
    count = 0
    for path in source.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in {".md", ".markdown"}:
            continue
        relative = path.relative_to(source)
        if relative.name.casefold() == "skill.md":
            relative = relative.with_name("UPSTREAM_SKILL.md")
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        content = path.read_text(encoding="utf-8")
        target.write_text(
            content.replace("SKILL.md", "UPSTREAM_SKILL.md"),
            encoding="utf-8",
        )
        shutil.copystat(path, target)
        count += 1
    return count


def copy_license(repo: Path, destination: Path) -> str | None:
    for name in ("LICENSE", "LICENSE.md", "LICENSE.txt"):
        source = repo / name
        if source.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            return hashlib.sha256(source.read_bytes()).hexdigest()
    return None


def clone(url: str, destination: Path, commit: str | None = None) -> dict[str, str]:
    if commit:
        run("git", "init", str(destination))
        run("git", "remote", "add", "origin", url, cwd=destination)
        run("git", "fetch", "--depth", "1", "origin", commit, cwd=destination)
        run("git", "checkout", "--detach", "FETCH_HEAD", cwd=destination)
    else:
        run("git", "clone", "--depth", "1", url, str(destination))
    return {
        "url": url,
        "commit": run("git", "rev-parse", "HEAD", cwd=destination),
        "commit_date": run("git", "show", "-s", "--format=%cI", "HEAD", cwd=destination),
    }


def write_index(stage: Path, counts: dict[str, tuple[str, int]]) -> None:
    lines = [
        "# Synced Security Knowledge",
        "",
        "Generated by `scripts/sync_sources.py`. Do not edit cached upstream files.",
        "",
    ]
    for name, (unit, count) in sorted(counts.items()):
        lines.append(f"- `{name}`: {count} {unit}")
    lines.extend(
        [
            "",
            "Search before reading:",
            "",
            "```bash",
            "rg -n -i '<keyword>' .",
            "```",
            "",
        ]
    )
    (stage / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def replace_tree(stage: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    previous = destination.with_name(f"{destination.name}.previous")
    if previous.exists():
        shutil.rmtree(previous)
    if destination.exists():
        destination.replace(previous)
    try:
        shutil.copytree(stage, destination)
    except Exception:
        if destination.exists():
            shutil.rmtree(destination)
        if previous.exists():
            previous.replace(destination)
        raise
    if previous.exists():
        shutil.rmtree(previous)


def approve_candidate(lock_path: Path) -> None:
    candidate_tree = CANDIDATE_ROOT / "upstreams"
    if not candidate_tree.is_dir() or not lock_path.is_file():
        raise ValueError("no reviewed source candidate is available")
    candidate = json.loads(lock_path.read_text(encoding="utf-8"))
    if candidate.get("review", {}).get("instruction_authority") is not False:
        raise ValueError("candidate trust policy is invalid")
    replace_tree(candidate_tree, UPSTREAMS)
    approved = {key: value for key, value in candidate.items() if key != "review"}
    (ROOT / "sources.lock.json").write_text(
        json.dumps(approved, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"[approved] sources={len(approved.get('sources', {}))}")
    print(f"[cache] {UPSTREAMS}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Synchronize pinned security knowledge sources")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="download latest sources into quarantine")
    mode.add_argument("--approve", action="store_true", help="activate the reviewed quarantined candidate")
    parser.add_argument("--reviewed", action="store_true", help="confirm candidate review before approval")
    args = parser.parse_args()
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    previous_lock = None
    lock_path = ROOT / "sources.lock.json"
    if lock_path.exists():
        try:
            previous_lock = json.loads(lock_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    candidate_lock_path = CANDIDATE_ROOT / "lock.json"
    if args.approve:
        if not args.reviewed:
            raise ValueError("source approval requires --reviewed")
        approve_candidate(candidate_lock_path)
        return
    if not args.refresh and not previous_lock:
        raise ValueError("sources.lock.json is required for pinned synchronization")
    lock: dict[str, object] = {
        "synced_at": datetime.now(timezone.utc).isoformat(),
        "sources": {},
    }
    counts: dict[str, tuple[str, int]] = {}

    work_parent = ROOT / ".work"
    work_parent.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="sync-", dir=work_parent) as temp:
        temp_root = Path(temp)
        stage = temp_root / "references"
        stage.mkdir()

        for name, source_config in config.items():
            repo = temp_root / f"repo-{name}"
            pinned = None if args.refresh else previous_lock["sources"][name]["commit"]
            metadata = clone(source_config["url"], repo, pinned)
            destination = stage / name

            if source_config.get("kind") == "payload-corpus":
                summary = build_catalog(
                    repo,
                    destination,
                    metadata,
                    previous_destination=UPSTREAMS / name,
                )
                count = int(summary["payloads"])
                metadata["catalog_files"] = int(summary["files"])
                metadata["payload_records"] = count
                counts[name] = ("payload records", count)
            elif "path" in source_config:
                count = copy_markdown_tree(repo / source_config["path"], destination)
                metadata["markdown_files"] = count
                counts[name] = ("Markdown files", count)
            else:
                count = 0
                for relative in source_config["paths"]:
                    source = repo / relative
                    count += copy_markdown_tree(source, destination / source.name)
                metadata["markdown_files"] = count
                counts[name] = ("Markdown files", count)

            license_sha256 = copy_license(repo, stage / "licenses" / f"{name}-LICENSE")
            if source_config.get("license_required", True) and not license_sha256:
                raise ValueError(f"source {name} has no recognized license file")
            metadata["license_sha256"] = license_sha256
            metadata["trust"] = str(source_config.get("trust") or "community")
            metadata["content_policy"] = "retrieval-only-untrusted"
            lock["sources"][name] = metadata

        write_index(stage, counts)
        if args.refresh:
            replace_tree(stage, CANDIDATE_ROOT / "upstreams")
        else:
            replace_tree(stage, UPSTREAMS)

    if args.refresh:
        candidate = {
            **lock,
            "review": {
                "status": "candidate",
                "instruction_authority": False,
                "required_checks": ["source-diff", "license", "privacy", "prompt-injection"],
            },
        }
        candidate_lock_path.parent.mkdir(parents=True, exist_ok=True)
        candidate_lock_path.write_text(
            json.dumps(candidate, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"[candidate] {candidate_lock_path}")
    for name, (unit, count) in sorted(counts.items()):
        print(f"[synced] {name}: {count} {unit}")
    print(f"[cache] {CANDIDATE_ROOT / 'upstreams' if args.refresh else UPSTREAMS}")


if __name__ == "__main__":
    main()
